// Define all menu categories and their items
export const menuCategories = [
    {
      id: "starters",
      name: "Starters",
      columns: 3,
      items: [
        { id: "arabic-spin-roll", name: "Arabic Spin Roll" },
        { id: "behari-spin-roll", name: "Behari Spin Roll" },
        { id: "calzone-chunks", name: "Calzone Chunks" },
        { id: "cheezy-sticks", name: "Cheezy Sticks" },
        { id: "flaming-wings-6pc", name: "Flaming Wings 6pc" },
        { id: "flaming-wings-12pc", name: "Flaming Wings 12pc" },
        { id: "lettuce", name: "Lettuce (30 Grm)" },
        { id: "oven-baked-wings-12pc", name: "Oven Baked Wings 12pc" },
        { id: "oven-baked-wings-6pc", name: "Oven Baked Wings 6pc" },
      ],
    },
    {
      id: "pizza-deals",
      name: "Pizza Deals",
      columns: 2,
      items: [
        { id: "small-pizza-deal", name: "Small Pizza Deal" },
        { id: "regular-pizza-deal", name: "Regular Pizza Deal" },
        { id: "large-pizza-deal", name: "Large Pizza Deal" },
      ],
    },
    {
      id: "burgerz",
      name: "Burgerz",
      columns: 2,
      items: [
        { id: "reggy-burger", name: "Reggy Burger" },
        { id: "bazinga", name: "Bazinga" },
      ],
    },
    {
      id: "cheezy-treats",
      name: "Cheezy Treats",
      columns: 2,
      items: [
        { id: "behari-kebab-pizza", name: "Behari Kebab Pizza" },
        { id: "cheezious-special-pizza", name: "Cheezious Special Pizza" },
        { id: "chicken-extreme-pizza", name: "Chicken Extreme Pizza" },
      ],
    },
    {
      id: "special-pizza",
      name: "Special Pizza",
      columns: 2,
      items: [
        { id: "crown-crust", name: "Crown Crust" },
        { id: "stuffed-crust", name: "Stuffed Crust" },
        { id: "beef-pepperoni", name: "Beef Pepperoni" },
        { id: "stuffed-cheese-pizza", name: "Stuffed Cheese Pizza" },
      ],
    },
    {
      id: "side-order",
      name: "Side Order",
      columns: 2,
      items: [
        { id: "chicken-nuggets-5pcs", name: "Chicken Nuggets 5PCS" },
        { id: "fried-chicken-1pcs", name: "Fried Chicken 1PCS" },
        { id: "fried-chicken-3pcs", name: "Fried Chicken 3PCS" },
        { id: "regular-fries", name: "Regular Fries" },
        { id: "large-fries", name: "Large Fries" },
      ],
    },
    {
      id: "somewhat-sooper",
      name: "Somewhat Sooper",
      columns: 3,
      items: [
        { id: "black-pepper-pizza", name: "Black Pepper Pizza" },
        { id: "cheese-lover-pizza", name: "Cheese Lover Pizza" },
        { id: "chicken-mushroom-pizza", name: "Chicken Mushroom Pizza" },
        { id: "chicken-supreme-pizza", name: "Chicken Supreme Pizza" },
        { id: "euro-pizza", name: "Euro Pizza" },
        { id: "pepperoni-pizza", name: "Pepperoni Pizza" },
        { id: "sausage-pizza", name: "Sausage Pizza" },
      ],
    },
    {
      id: "pasta",
      name: "Pasta",
      columns: 2,
      items: [
        { id: "crunchy-chicken-pasta", name: "Crunchy Chicken Pasta" },
        { id: "fettuccine-alfredo-pasta", name: "Fettuccine Alfredo Pasta" },
      ],
    },
    {
      id: "somewhat-amazing",
      name: "Somewhat Amazing",
      columns: 2,
      smallText: true,
      items: [
        { id: "amazing-deal-1", name: "S.Amazing Deal-1 (2 Bazinga + Fries + 2 Drinks)" },
        { id: "amazing-deal-2", name: "S.Amazing Deal-2 (2 Bazinga + Chic Pcs + Large Fries + 2 Drinks)" },
        { id: "amazing-deal-3", name: "S.Amazing Deal-3 (3 Bazinga + Large Fries + 1L Drink)" },
        { id: "amazing-deal-4", name: "S.Amazing Deal-4 (3 Bazinga + Chic Pcs + 1L Drink)" },
      ],
    },
    {
      id: "somewhat-local",
      name: "Somewhat Local",
      columns: 2,
      items: [
        { id: "chicken-fajita-pizza", name: "Chicken Fajita Pizza" },
        { id: "chicken-lover-pizza", name: "Chicken Lover Pizza" },
        { id: "chicken-tandoori-pizza", name: "Chicken Tandoori Pizza" },
        { id: "chicken-tikka-pizza", name: "Chicken Tikka Pizza" },
        { id: "hot-n-spicy-pizza", name: "Hot n Spicy Pizza" },
        { id: "vegetable-pizza", name: "Vegetable Pizza" },
      ],
    },
    {
      id: "sweetness",
      name: "Sweetness",
      columns: 2,
      smallText: true,
      items: [
        { id: "chocolate-double-scoop", name: "Chocolate Double Scoop IceCream" },
        { id: "king-kulfa-double-scoop", name: "King Kulfa Double Scoop IceCream" },
        { id: "mango-double-scoop", name: "Mango Double Scoop IceCream" },
        { id: "tutti-fruity-double-scoop", name: "Tutti Fruity Icecream Double Scoop Icecream" },
        { id: "strawberry-double-scoop", name: "Strawberry Double Scoop IceCream" },
        { id: "vanilla-double-scoop", name: "Vanilla Double Scoop IceCream" },
      ],
    },
    {
      id: "sandwiches-platters",
      name: "Sandwiches and Platters",
      columns: 2,
      items: [
        { id: "special-roasted-plater", name: "Special Roasted Plater" },
        { id: "mexican-sandwich", name: "Mexican Sandwich" },
        { id: "pizza-stacker", name: "Pizza Stacker" },
        { id: "classic-roll-plater", name: "Classic Roll Plater" },
        { id: "euro-sandwich", name: "Euro Sandwich" },
        { id: "classic-roll-plater-2", name: "Classic Roll Plater" },
        { id: "bihari-sandwich", name: "Bihari Sandwich" },
        { id: "arabic-roll-plater", name: "Arabic Roll Plater" },
      ],
    },
    {
      id: "wraps",
      name: "Wraps",
      columns: 1,
      items: [{ id: "bazooka", name: "Bazooka" }],
    },
    {
      id: "drinks",
      name: "Drinks",
      columns: 2,
      items: [
        { id: "7up", name: "7UP" },
        { id: "pepsi", name: "Pepsi" },
        { id: "marinda", name: "Marinda" },
        { id: "regular", name: "Regular" },
        { id: "nr", name: "NR" },
        { id: "murree", name: "Murree" },
        { id: "250ml-juice", name: "250ML Juice" },
        { id: "aquafina-500ml", name: "Aquafina 500ML" },
      ],
    },
    {
      id: "addons",
      name: "Addons",
      columns: 2,
      smallText: true,
      items: [
        { id: "extra-tikka", name: "Extra Tikka" },
        { id: "extra-black-pepper", name: "Extra Black Pepper" },
        { id: "extra-cheese", name: "Extra Cheese" },
        { id: "extra-fajita", name: "Extra Fajita" },
        { id: "extra-grilled-smoke", name: "Extra Grilled/Smoke" },
        { id: "extra-jamaican", name: "Extra Jamaican" },
        { id: "extra-mughlai", name: "Extra Mughlai" },
        { id: "deal-with-addition", name: "Deal With Addition of (Reg Drink & Reg Fries)" },
        { id: "mayo-dip-sauce", name: "Mayo Dip Sauce (Pack)" },
      ],
    },
    {
      id: "desserts",
      name: "Desserts",
      columns: 2,
      items: [
        { id: "cheese-cake", name: "Cheese Cake" },
        { id: "cake", name: "Cake" },
        { id: "milk-cake", name: "Milk Cake" },
      ],
    },
  ]
  
  