import React from 'react';
import { Box, Typography, Divider } from '@mui/material';

const XReport = ({ reportData }) => {
  // Function to format lines with dots
  const formatLine = (label, value, totalWidth = 32) => {
    const labelLength = label.length;
    const valueLength = value.toString().length;
    const dotsLength = totalWidth - labelLength - valueLength;
    const dots = '.'.repeat(dotsLength > 0 ? dotsLength : 0);
    return `${label}${dots}${value}`;
  };

 // Extracting values from reportData
  const taxes = reportData.taxes || 0;
  const tax1Charges = taxes / 2;
  const discounts = reportData.discounts || 0;
  const rounded = reportData.rounded || 0;
  const voidedLines = reportData.voidedLines || 0;
  const customerOrders = reportData.customerOrders || {
    placed: 0,
    edited: 0,
    depositCollected: 0,
    canceled: 0,
    voidedLines: 0,
    charges: 0,
    depositRefunded: 0,
    depositRedeemed: 0,
  };
  const statistics = {
    sales: reportData.salesCount || 0,
    customerSales: reportData.customerSalesCount || 0,
    voidedSales: reportData.voidedSalesCount || 0,
    openDrawer: reportData.openDrawerCount || 0,
  };

  return (
    <Box
      sx={{
        fontFamily: '"VT323", monospace',
        fontSize: '10px', 
        lineHeight: '1.0', 
        color: '#000',
      }}
    >
      {/* Header */}
      <Typography
        variant="h6"
        align="center"
        sx={{
          fontFamily: '"VT323", monospace',
          fontWeight: 'normal',
          fontSize: '12px',
          marginBottom: '1px',
        }}
      >
        X-Report
      </Typography>
      <Divider sx={{ borderColor: '#000', margin: '1px 0' }} />

      {/* Store and Employee Info */}
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Date', reportData.date)}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Generated by', reportData.employeeName)}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Time', reportData.time)}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Register', reportData.register)}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Start date', reportData.startDate)}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('End Date', reportData.endDate)}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Start time', reportData.startTime)}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('End time', reportData.endTime)}
      </Typography>
      <Divider sx={{ borderColor: '#000', margin: '1px 0' }} />

      {/* Total Amounts */}
      <Typography
        sx={{
          fontFamily: '"VT323", monospace',
          fontWeight: 'normal',
          marginTop: '1px',
          whiteSpace: 'nowrap',
        }}
      >
        Total amounts
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Sales:', reportData.sales.toFixed(2))}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Gift cards:', (0).toFixed(2))}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Cashed out gift card amount:', (0).toFixed(2))}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Returns:', `(${reportData.returns.toFixed(2)})`)}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Taxes:', taxes.toFixed(2))}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Tax1 charges:', tax1Charges.toFixed(2))}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Discounts:', discounts.toFixed(2))}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Rounded:', rounded.toFixed(2))}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Voided lines:', voidedLines.toFixed(2))}
      </Typography>
      <Divider sx={{ borderColor: '#000', margin: '1px 0' }} />

      {/* Customer Orders */}
      <Typography
        sx={{
          fontFamily: '"VT323", monospace',
          fontWeight: 'normal',
          marginTop: '1px',
          whiteSpace: 'nowrap',
        }}
      >
        Customer orders
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Placed:', customerOrders.placed.toFixed(2))}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Edited:', customerOrders.edited.toFixed(2))}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Deposit collected:', customerOrders.depositCollected.toFixed(2))}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Canceled:', customerOrders.canceled.toFixed(2))}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Voided lines:', customerOrders.voidedLines.toFixed(2))}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Charges:', customerOrders.charges.toFixed(2))}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Deposit refunded:', customerOrders.depositRefunded.toFixed(2))}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Deposit redeemed:', customerOrders.depositRedeemed.toFixed(2))}
      </Typography>
      <Divider sx={{ borderColor: '#000', margin: '1px 0' }} />

      {/* Statistics */}
      <Typography
        sx={{
          fontFamily: '"VT323", monospace',
          fontWeight: 'normal',
          marginTop: '1px',
          whiteSpace: 'nowrap',
        }}
      >
        Statistics
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Sales:', statistics.sales)}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Customer sales:', statistics.customerSales)}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Voided sales:', statistics.voidedSales)}
      </Typography>
      <Typography sx={{ fontFamily: '"VT323", monospace', whiteSpace: 'nowrap' }}>
        {formatLine('Open drawer:', statistics.openDrawer)}
      </Typography>
    </Box>
  );
};

export default XReport;